#! /bin/bash
sync_dir="/mnt/sync/"
data_dir="$sync_dir/data/"
conf_dir="$sync_dir/conf/"
files_dir="$data_dir$(< /dev/urandom tr -dc _A-Z-a-z-0-9 | head -c${1:-32};)/"
device_name="user"$RANDOM
key="AFIW2OLP2N3TZZEDIAU77PWHVPQMJFTYZ"
mkdir -p $data_dir
mkdir -p $conf_dir
mkdir -p $files_dir


script='{'
script+='"device_name": "${device_name}",'
script+='"listening_port" : 0, // 0 - randomize port'
script+='"storage_path" : "/mnt/sync/conf/",'
script+='"use_upnp" : true,'
script+='"download_limit" : 0,'
script+='"upload_limit" : 0,'
script+='"webui" :'
script+='{'
script+='"listen" : "0.0.0.0:8888" // remove field to disable WebUI'
script+=',"login" : "admin"'
script+=',"password" : "" // (not recommended, better use password_hash_unified)'
script+='}'
script+=','
script+='"shared_folders" :'
script+='['
script+='{'
script+='"secret" : "${key}", // required field - use --generate-secret in command line to create new secret'
script+='"dir" : "${files_dir}", // * required field'
script+='"use_relay_server" : true, //  use relay server when direct connection fails'
script+='"use_tracker" : true,'
script+='"search_lan" : true,'
script+='"use_sync_trash" : true, // enable SyncArchive to store files deleted on remote devices'
script+='"overwrite_changes" : false, // restore modified files to original version, ONLY for Read-Only folders'
script+='"selective_sync" : false, // add folder in selective sync mode'
script+='"known_hosts" : // specify hosts to attempt connection without additional search'
script+='[]'
script+='}'
script+=']'
script+='}'


echo -e $script > $conf_dir"sync.conf"
#exec /usr/bin/rslsync --nodaemon $*